# Generated by Django 5.0.3 on 2024-03-27 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_ticket_passenger"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="passenger",
        ),
    ]
