# Generated by Django 5.0.3 on 2024-03-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_remove_ticket_passenger"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="passenger",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
