# Generated by Django 5.0.4 on 2024-04-06 10:07

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0004_ticket_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='image',
            field=
            models.ImageField(
                null=True,
                upload_to=airport.models.airplane_image_file_path
            ),
        ),
    ]
